services:
  mongo:
    image: mongo:5
    command: --nojournal
  
  orion:
    image: fiware/orion #-ld:1.1.0
    depends_on:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"

  truffle-ganache:
    image: trufflesuite/ganache
    ports:
      - "8545:8545"
